/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BuyMeCoffeeInterface extends ethers.utils.Interface {
  functions: {
    "buyCoffee(string,string)": FunctionFragment;
    "getMemos()": FunctionFragment;
    "withdrawTips()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyCoffee",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getMemos", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawTips",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyCoffee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMemos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTips",
    data: BytesLike
  ): Result;

  events: {
    "NewMemo(address,uint256,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewMemo"): EventFragment;
}

export type NewMemoEvent = TypedEvent<
  [string, BigNumber, string, string] & {
    from: string;
    timestamp: BigNumber;
    name: string;
    message: string;
  }
>;

export class BuyMeCoffee extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BuyMeCoffeeInterface;

  functions: {
    buyCoffee(
      _name: string,
      _message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMemos(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, string, string] & {
          from: string;
          timestamp: BigNumber;
          name: string;
          message: string;
        })[]
      ]
    >;

    withdrawTips(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyCoffee(
    _name: string,
    _message: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMemos(
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, string, string] & {
      from: string;
      timestamp: BigNumber;
      name: string;
      message: string;
    })[]
  >;

  withdrawTips(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyCoffee(
      _name: string,
      _message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getMemos(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, string, string] & {
        from: string;
        timestamp: BigNumber;
        name: string;
        message: string;
      })[]
    >;

    withdrawTips(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "NewMemo(address,uint256,string,string)"(
      from?: string | null,
      timestamp?: null,
      name?: null,
      message?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string],
      { from: string; timestamp: BigNumber; name: string; message: string }
    >;

    NewMemo(
      from?: string | null,
      timestamp?: null,
      name?: null,
      message?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string],
      { from: string; timestamp: BigNumber; name: string; message: string }
    >;
  };

  estimateGas: {
    buyCoffee(
      _name: string,
      _message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMemos(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawTips(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyCoffee(
      _name: string,
      _message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMemos(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawTips(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
